In [82]:
import pandas as pd
import matplotlib as plt 
import numpy as np 
import seaborn as sns

df = pd.read_csv("train.csv")
validation = pd.read_csv("test.csv")



In [83]:
df.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

# EDA

In [84]:
df.dtypes

PassengerId      object
HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported        bool
dtype: object

In [85]:
df.describe()

Age   RoomService     FoodCourt  ShoppingMall           Spa  \
count  8514.000000   8512.000000   8510.000000   8485.000000   8510.000000   
mean     28.827930    224.687617    458.077203    173.729169    311.138778   
std      14.489021    666.717663   1611.489240    604.696458   1136.705535   
min       0.000000      0.000000      0.000000      0.000000      0.000000   
25%      19.000000      0.000000      0.000000      0.000000      0.000000   
50%      27.000000      0.000000      0.000000      0.000000      0.000000   
75%      38.000000     47.000000     76.000000     27.000000     59.000000   
max      79.000000  14327.000000  29813.000000  23492.000000  22408.000000   

             VRDeck  
count   8505.000000  
mean     304.854791  
std     1145.717189  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%       46.000000  
max    24133.000000

In [86]:
df.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

## Preparacion 

In [87]:
df.drop(["PassengerId","Cabin","Name"], axis=1, inplace=True)
df

HomePlanet CryoSleep    Destination   Age    VIP  RoomService  FoodCourt  \
0        Europa     False    TRAPPIST-1e  39.0  False          0.0        0.0   
1         Earth     False    TRAPPIST-1e  24.0  False        109.0        9.0   
2        Europa     False    TRAPPIST-1e  58.0   True         43.0     3576.0   
3        Europa     False    TRAPPIST-1e  33.0  False          0.0     1283.0   
4         Earth     False    TRAPPIST-1e  16.0  False        303.0       70.0   
...         ...       ...            ...   ...    ...          ...        ...   
8688     Europa     False    55 Cancri e  41.0   True          0.0     6819.0   
8689      Earth      True  PSO J318.5-22  18.0  False          0.0        0.0   
8690      Earth     False    TRAPPIST-1e  26.0  False          0.0        0.0   
8691     Europa     False    55 Cancri e  32.0  False          0.0     1049.0   
8692     Europa     False    TRAPPIST-1e  44.0  False        126.0     4688.0   

      ShoppingMall     Spa  VRDeck  Transported  
0              0.0     0.0     0.0        False  
1             25.0   549.0    44.0         True  
2              0.0  6715.0    49.0        False  
3            371.0  3329.0   193.0        False  
4            151.0   565.0     2.0         True  
...            ...     ...     ...          ...  
8688           0.0  1643.0    74.0        False  
8689           0.0     0.0     0.0        False  
8690        1872.0     1.0     0.0         True  
8691           0.0   353.0  3235.0        False  
8692           0.0     0.0    12.0         True  

[8693 rows x 11 columns]

### Tratamiento de datos 

In [88]:
# Tratamiento valores nulos de columna Age

def fill_null(df):
    #columna Age
    age_median = df["Age"].mean()
    df["Age"].fillna(age_median,inplace= True)
    validation["Age"].fillna(age_median,inplace= True)
    # Columna HomePlanet
    homeplanet_mode = df["HomePlanet"].mode()[0]
    df["HomePlanet"].fillna(homeplanet_mode,inplace= True)
    validation["HomePlanet"].fillna(homeplanet_mode,inplace= True)
    #Columna Destination
    Destination_mode = df["Destination"].mode()[0]
    df["Destination"].fillna(Destination_mode,inplace= True)
    validation["Destination"].fillna(Destination_mode,inplace= True)
    #Columna VIP CryoSleep
    df["CryoSleep"].astype(bool)
    df["CryoSleep"].fillna(False,inplace= True)
    validation["CryoSleep"].fillna(False,inplace= True)
    #Columna 
    df["VIP"].astype(bool)
    df["VIP"].fillna(False,inplace= True)
    validation["VIP"].fillna(False,inplace= True)
    #Columna RoomService
    df["RoomService"].fillna(0.0,inplace=True)
    validation["RoomService"].fillna(0.0,inplace= True)
    #Columna FoodCourt
    df["FoodCourt"].fillna(0.0,inplace= True)
    validation["FoodCourt"].fillna(0.0,inplace= True)
    #Columna ShoppingMall
    df["ShoppingMall"].fillna(0.0,inplace= True)
    validation["ShoppingMall"].fillna(0.0,inplace= True)
    #Columna Spa
    df["Spa"].fillna(0.0,inplace= True)
    validation["Spa"].fillna(0.0,inplace= True)
    #Columna VRDeck
    df["VRDeck"].fillna(0.0,inplace= True)
    validation["VRDeck"].fillna(0.0,inplace= True)
    return (df)
df=fill_null(df)

print("Porcentaje de valores nulos"+str((df.isnull().sum().sum()/len(df))*100))


Porcentaje de valores nulos0.0


In [89]:
df.head

<bound method NDFrame.head of      HomePlanet  CryoSleep    Destination   Age    VIP  RoomService  \
0        Europa      False    TRAPPIST-1e  39.0  False          0.0   
1         Earth      False    TRAPPIST-1e  24.0  False        109.0   
2        Europa      False    TRAPPIST-1e  58.0   True         43.0   
3        Europa      False    TRAPPIST-1e  33.0  False          0.0   
4         Earth      False    TRAPPIST-1e  16.0  False        303.0   
...         ...        ...            ...   ...    ...          ...   
8688     Europa      False    55 Cancri e  41.0   True          0.0   
8689      Earth       True  PSO J318.5-22  18.0  False          0.0   
8690      Earth      False    TRAPPIST-1e  26.0  False          0.0   
8691     Europa      False    55 Cancri e  32.0  False          0.0   
8692     Europa      False    TRAPPIST-1e  44.0  False        126.0   

      FoodCourt  ShoppingMall     Spa  VRDeck  Transported  
0           0.0           0.0     0.0     0.0        Fal

In [90]:
from sklearn.preprocessing import OneHotEncoder

Nominal_codificador=OneHotEncoder(sparse=False)
Nominal_codificador.fit_transform(df[['Transported']] )

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [91]:
Nominal_codificador.categories_

[array([False,  True])]

In [92]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder  

In [93]:
categorical_list = ["HomePlanet", "Destination", "VIP", "CryoSleep"]
numeric_list = ["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]

In [94]:
numeric_transformer= Pipeline ( steps= [ ('scaler',StandardScaler() ) ] )
categorical_transformer= Pipeline ( steps= [ ('onehot',OneHotEncoder() ) ]  )                    

In [95]:
#Definir los transformadores, se utilizara cuando se aplicaran los algoritmos a machine learning

transformer = ColumnTransformer ( [
('cat',categorical_transformer,categorical_list) , ('num',numeric_transformer,numeric_list)
])


In [96]:
X = df.drop("Transported", axis=1)
y = df["Transported"]

In [97]:
X.head()

HomePlanet  CryoSleep  Destination   Age    VIP  RoomService  FoodCourt  \
0     Europa      False  TRAPPIST-1e  39.0  False          0.0        0.0   
1      Earth      False  TRAPPIST-1e  24.0  False        109.0        9.0   
2     Europa      False  TRAPPIST-1e  58.0   True         43.0     3576.0   
3     Europa      False  TRAPPIST-1e  33.0  False          0.0     1283.0   
4      Earth      False  TRAPPIST-1e  16.0  False        303.0       70.0   

   ShoppingMall     Spa  VRDeck  
0           0.0     0.0     0.0  
1          25.0   549.0    44.0  
2           0.0  6715.0    49.0  
3         371.0  3329.0   193.0  
4         151.0   565.0     2.0

In [98]:
y.head()

0    False
1     True
2    False
3    False
4     True
Name: Transported, dtype: bool

In [99]:
from sklearn.model_selection import train_test_split

# given:
# features: xs
# ground truth: ys

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.33,
                                                    random_state=0)

In [100]:
#aca me muestra la cantidad de datos a usar en training y test

X_train.shape,X_test.shape,y_train.shape,y_test.shape

((5824, 10), (2869, 10), (5824,), (2869,))

### Entrenar

In [101]:
from sklearn.linear_model import LogisticRegression
logistic_regression=LogisticRegression()

In [102]:
#pipeline de la prediccion completa

model_logistic_regression = Pipeline( [
    ('transformer',transformer),
    ('logistic_regression', logistic_regression)
    ] )

In [103]:
model_logistic_regression .fit(X_train,y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['HomePlanet', 'Destination',
                                                   'VIP', 'CryoSleep']),
                                                 ('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'RoomService',
                                                   'FoodCourt', 'ShoppingMall',
                                                   'Spa', 'VRDeck'])])),
                ('logistic_regression', LogisticRegression())])

In [104]:
#probamos con pocos datos
muestra_datos=X_test.iloc[4:]

model_logistic_regression.predict(muestra_datos)

array([ True, False, False, ...,  True,  True, False])

In [105]:
#comparamos con los valores reales
list(y_test.iloc[:4])

[True, True, False, False]

In [111]:
# Definimos una funcion que nos devuelva el score, mean y standard deviation

def display_scores(scores):
    print('Scores:',scores)
    print('Mean:',scores.mean())
    print('Standard Deviation:',scores.std())

In [129]:
display_scores = dest_count / len(df)
dest_percent

TRAPPIST-1e      0.701369
55 Cancri e      0.207063
PSO J318.5-22    0.091568
Name: Destination, dtype: float64

In [124]:
home_count = df["HomePlanet"].value_counts()
home_count

Earth     4803
Europa    2131
Mars      1759
Name: HomePlanet, dtype: int64

In [131]:
dest_count = df["Destination"].value_counts()

In [128]:
# Importing the dependancies
from sklearn import metrics
# Predicted values
y_pred = ["a", "b", "c", "a", "b"]
# Actual values
y_act = ["a", "b", "c", "c", "a"]
# Printing the confusion matrix
# The columns will show the instances predicted for each label,
# and the rows will show the actual number of instances for each label.
print(metrics.confusion_matrix(y_act, y_pred, labels=["a", "b", "c"]))
# Printing the precision and recall, among other metrics
print(metrics.classification_report(y_act, y_pred, labels=["a", 
"b","c"]))

[[1 1 0]
 [0 1 0]
 [1 0 1]]
              precision    recall  f1-score   support

           a       0.50      0.50      0.50         2
           b       0.50      1.00      0.67         1
           c       1.00      0.50      0.67         2

    accuracy                           0.60         5
   macro avg       0.67      0.67      0.61         5
weighted avg       0.70      0.60      0.60         5

